service: npzr

plugins:
  - serverless-stack-output
  - serverless-dynamodb-local
  - serverless-appsync-plugin
  - serverless-pseudo-parameters
  - serverless-s3-sync

provider:
  name: aws
  runtime: java8
  stage: '${opt:stage, ''dev''}'
  region: eu-west-1
  profile: npzr
  cfLogs: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource:
        - { "Fn::GetAtt": ["GameDynamoDBTable", "Arn" ] }

custom:
  gameTableName: 'game-${self:provider.stage}'
  siteName: www-${self:provider.stage}.${self:custom.hostedZoneName}
  hostedZoneName: saskcowgames.com
  aliasHostedZoneId: Z1BKCTXD74EZPE
  aliasDNSName: s3-website-eu-west-1.amazonaws.com
  userPoolName: 'npzrUserPool${self:provider.stage}'
  accountId: #{AWS::AccountId}
  output:
    handler: output.handler
    file: outputs.yaml
  appSync:
    name: npzr
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      defaultAction: ALLOW
      userPoolId: { Ref: UserPool }
    mappingTemplates:
      - dataSource: gameLambdaDS
        type: Mutation
        field: createGame
        request: 'createGameReq.vtl'
        response: 'createGameRes.vtl'
    dataSources:
      - type: AWS_LAMBDA
        name: gameLambdaDS
        description: "Lambda datasource"
        config:
          lambdaFunctionArn: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-createGame"
          serviceRoleArn: { "Fn::GetAtt": ["AppSyncServiceRole", "Arn" ] }
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
      inMemory: true
  s3Sync:
    - bucketName: ${self:custom.customDomain.domainName}
      localDir: ui/build
      acl: public-read
      followSymlinks: true
      defaultContentType: text/html
      params:
        - index.html:
            CacheControl: 'no-cache'
        - "*.js":
            CacheControl: "public, max-age: 3600"
  domains:
    prod: npzr-api.${self:custom.hostedZoneName}
    staging: npzr-api-stage.${self:custom.hostedZoneName}
    dev: npzr-api-dev.${self:custom.hostedZoneName}
  customDomain:
    domainName: ${self:custom.domains.${self:provider.stage}}
    basePath: ''
    stage: ${self:provider.stage}
    certificateName: "*.${self:custom.hostedZoneName}"
    createRoute53Record: true
    endpointType: 'regional'

package:
  artifact: api-lambda/build/libs/api-lambda-dev-all.jar

functions:
  createGame:
    handler: com.pyruby.npzr.handlers.CreateGameHandler

resources:
  - '${file(resources/cognito.yml)}'
  - '${file(resources/dynamo.yml)}'
  - Resources:
      CreateGameLogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
          RetentionInDays: "7"
      staticBucket:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: ${self:custom.customDomain.domainName}
          AccessControl: PublicRead
          WebsiteConfiguration:
            IndexDocument: index.html
            ErrorDocument: error.html
          CorsConfiguration:
            CorsRules:
              - AllowedOrigins:
                  - '*'
                AllowedHeaders:
                  - '*'
                AllowedMethods:
                  - GET
                  - HEAD
                MaxAge: 3000
      AppSyncServiceRole:
        Type: "AWS::IAM::Role"
        Properties:
          RoleName: "AppSyncServiceRole"
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Principal:
                  Service:
                    - "appsync.amazonaws.com"
                Action:
                  - "sts:AssumeRole"
          Policies:
            - PolicyName: "Lambda-AppSyncServiceRole-Policy"
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: "Allow"
                    Action:
                      - "lambda:invokeFunction"
                    Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-createGame"
      DnsRecord:
        Type: "AWS::Route53::RecordSet"
        Properties:
          AliasTarget:
            DNSName: ${self:custom.aliasDNSName}
            HostedZoneId: ${self:custom.aliasHostedZoneId}
          HostedZoneName: ${self:custom.hostedZoneName}.
          Name:
            Ref: staticBucket
          Type: A
